version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - echo "Building commit:" && git log -1 --oneline
      - echo "IMAGE_TAG=$IMAGE_TAG"
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -f rise-portal/Dockerfile.debian -t rise-portal:$IMAGE_TAG .
      - docker tag rise-portal:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/rise-portal:latest
      - docker tag rise-portal:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/rise-portal:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/rise-portal:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/rise-portal:$IMAGE_TAG
      - echo Updating ECS service...
      - aws ecs update-service --cluster refuge-apps --service rise-portal --force-new-deployment --region $AWS_DEFAULT_REGION
      - echo Deploy triggered

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    AWS_ACCOUNT_ID: 637131561301
