// <auto-generated />
using System;
using FortressNexus.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FortressNexus.Web.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260402040040_AddSubmissionFilesJunctionTable")]
    partial class AddSubmissionFilesJunctionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.ArtifactSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdoOrganization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ado_organization");

                    b.Property<string>("AdoProjectId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ado_project_id");

                    b.Property<string>("AdoProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ado_project_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("longtext")
                        .HasColumnName("error_detail");

                    b.Property<string>("ProcessTemplateTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("process_template_type_id");

                    b.Property<int>("SpecDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("spec_document_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SpecDocumentId");

                    b.ToTable("artifact_sets", (string)null);
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.SpecDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("approved_by");

                    b.Property<int>("CompletionTokensUsed")
                        .HasColumnType("int")
                        .HasColumnName("completion_tokens_used");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("edited_at");

                    b.Property<string>("EditedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("edited_by");

                    b.Property<string>("EditedContent")
                        .HasColumnType("longtext")
                        .HasColumnName("edited_content");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("generated_by");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_approved");

                    b.Property<int>("PromptTokensUsed")
                        .HasColumnType("int")
                        .HasColumnName("prompt_tokens_used");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("spec_documents", (string)null);
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveSpecDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("active_spec_document_id");

                    b.Property<string>("FeatureArea")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("feature_area");

                    b.Property<int?>("MockupFileId")
                        .HasColumnType("int")
                        .HasColumnName("mockup_file_id");

                    b.Property<string>("NarrativeText")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("narrative_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("submitted_by");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("MockupFileId");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.SubmissionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    b.Property<int>("UploadedFileId")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_file_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("UploadedFileId");

                    b.ToTable("submission_files", (string)null);
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int>("FileType")
                        .HasColumnType("int")
                        .HasColumnName("file_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ProcessedText")
                        .HasColumnType("longtext")
                        .HasColumnName("processed_text");

                    b.Property<string>("S3Bucket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("s3_bucket");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("s3_key");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.ToTable("uploaded_files", (string)null);
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.WorkItemRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdoWorkItemId")
                        .HasColumnType("int")
                        .HasColumnName("ado_work_item_id");

                    b.Property<string>("AdoWorkItemUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ado_work_item_url");

                    b.Property<int>("ArtifactSetId")
                        .HasColumnType("int")
                        .HasColumnName("artifact_set_id");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("error_detail");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<string>("WorkItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("work_item_type");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactSetId");

                    b.ToTable("work_item_records", (string)null);
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.ArtifactSet", b =>
                {
                    b.HasOne("FortressNexus.Web.Models.Entities.SpecDocument", "SpecDocument")
                        .WithMany("ArtifactSets")
                        .HasForeignKey("SpecDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SpecDocument");
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.SpecDocument", b =>
                {
                    b.HasOne("FortressNexus.Web.Models.Entities.Submission", "Submission")
                        .WithMany("SpecDocuments")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.Submission", b =>
                {
                    b.HasOne("FortressNexus.Web.Models.Entities.UploadedFile", "MockupFile")
                        .WithMany()
                        .HasForeignKey("MockupFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MockupFile");
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.SubmissionFile", b =>
                {
                    b.HasOne("FortressNexus.Web.Models.Entities.Submission", "Submission")
                        .WithMany("SubmissionFiles")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FortressNexus.Web.Models.Entities.UploadedFile", "UploadedFile")
                        .WithMany("SubmissionFiles")
                        .HasForeignKey("UploadedFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.WorkItemRecord", b =>
                {
                    b.HasOne("FortressNexus.Web.Models.Entities.ArtifactSet", "ArtifactSet")
                        .WithMany("WorkItemRecords")
                        .HasForeignKey("ArtifactSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtifactSet");
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.ArtifactSet", b =>
                {
                    b.Navigation("WorkItemRecords");
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.SpecDocument", b =>
                {
                    b.Navigation("ArtifactSets");
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.Submission", b =>
                {
                    b.Navigation("SpecDocuments");

                    b.Navigation("SubmissionFiles");
                });

            modelBuilder.Entity("FortressNexus.Web.Models.Entities.UploadedFile", b =>
                {
                    b.Navigation("SubmissionFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
